# These are supported funding model platforms

github: imshota1009
# patreon: # your Patreon username
# open_collective: # your Open Collective username
# ko_fi: # your Ko-fi username
# tidelift: # your Tidelift package name
# community_bridge: # your Community Bridge project name
# liberapay: # your Liberapay username
# issuehunt: # your IssueHunt username
# otechie: # your Otechie username
# lfx_crowdfunding: # your LFX Crowdfunding project name
# custom: ['https://example.com/sponsor']
